package no.nav.btn

const val TOPIC_MELDING_SENDT = "aapen-btn-meldingSendt"
const val TOPIC_MELDING_LEST = "privat-btn-meldingLest"
const val TOPIC_MELDING_JOURNALFOERT = "privat-btn-meldingJournalfoert"
const val TOPIC_MELDING_ARKIVERT = "privat-btn-meldingArkivert"
const val TOPIC_MELDING_OPERASJON_VELLYKKET = "privat-btn-meldingOperasjonVellykket"
const val TOPIC_JOURNALFOR_MELDING_FEILET = "privat-btn-journalfoeringFeilet"
const val TOPIC_OPPRETT_OPPGAVE_FEILET = "privat-btn-opprettOppgaveFeilet"
const val TOPIC_AVSLUTT_OPPGAVE_FEILET = "privat-btn-avsluttOppgaveFeilet"
const val TOPIC_OPPRETT_VARSEL_FEILET = "privat-btn-opprettVarselFeilet"
const val TOPIC_STOPP_REVARSEL_FEILET = "privat-btn-stoppRevarselFeilet"
const val TOPIC_ARKIVER_MELDING_FEILET = "privat-btn-arkiverMeldingFeilet"
const val TOPIC_RAPPORTERING_SAK_OG_BEHANDLING_RETRY = "privat-btn-rapporteringSakOgBehandlingFeilet"
const val TOPIC_DEAD_LETTER = "privat-btn-deadLetter"
