package no.nav.btn

const val TOPIC_MELDING = "btn-melding"
const val TOPIC_MELDING_LEST = "btn-melding-lest"
const val TOPIC_JOURNALFOR_MELDING = "btn-journalfor"
const val TOPIC_JOURNALFOR_MELDING_RETRY = "btn-journalfor-retry"
const val TOPIC_MELDING_TIL_FAGSYSTEM = "btn-melding-til-fagsystem"
const val TOPIC_METADATA_TIL_LAGRING = "btn-melding-til-lagring"
const val TOPIC_OPPRETT_OPPGAVE_RETRY = "btn-opprett-oppgave-retry"
const val TOPIC_AVSLUTT_OPPGAVE_RETRY = "btn-avslutt-oppgave-retry"
const val TOPIC_OPPRETT_VARSEL_RETRY = "btn-opprett-varsel-retry"
const val TOPIC_STOPP_REVARSEL_RETRY = "btn-stopp-revarsel-retry"
const val TOPIC_ARKIVER_MELDING_RETRY = "btn-arkiver-melding-retry"
const val TOPIC_RAPPORT_SAK_OG_BEHANDLING_RETRY = "btn-rapport-sak-og-behandling-retry"
const val TOPIC_DEAD_LETTER = "btn-dead-letter"